### ISSUE TITLE
Is there a way do disable the xmldoc highlight?

### ISSUE THREAD

**Issue by jchain** [nickspoons/vim-cs#18]
I've found the colorful highlighting in "///" xmldoc is a bit annoying. I just want a plain comment color. Is there a way to disable the xml highlighting in "///" comments? Thanks.

**Comment by nickspoons** [comment]
The XML comment highlighting includes XML syntax highlighting. You can disable that by just overriding [line 96](https://github.com/nickspoons/vim-cs/blob/master/syntax/cs.vim#L96) without the `@csXml` include.

You can do it in an autocmd but the easiest way is to make a `~/.vim/after/syntax/cs.vim` file containing:

```vim
syn match csXmlComment "///.*$" contains=csXmlCommentLeader,@Spell keepend
```

**Comment by jchain** [comment]
It works. Thanks!
