### ISSUE TITLE
It seems the 'record' keyword cannot be highlighted

### ISSUE THREAD

**Issue by sharpbladepan** [nickspoons/vim-cs#57]
syn keyword	csStorage	enum interface namespace struct record

Adding 'record' to the end of line 27 of syntax/cs.vim seems work for my file.

**Comment by nickspoons** [comment]
I believe @dkearns is working on a more complete fix than just adding the keyword, according to #36

**Comment by sharpbladepan** [comment]
Thanks for updating.
