### ISSUE TITLE
Disagreements with syntax: comparison with oranget/vim-csharp

### ISSUE THREAD

**Issue by idbrii** [nickspoons/vim-cs#6]
I finally setup your repo to clobber syntax from oranget/vim-csharp and I thought I'd share some complaints about the syntax highlighting. I'm using my own colorscheme [sandydune](https://github.com/idbrii/vim-sandydune), but think these complaints hold up on other schemes (desert, lucius, and apprentice).

I've added these to my after/syntax/cs.vim:

    " Don't add special highlight to end colons.
    hi link	csEndColon	NONE
    " Don't like operators looking like constants.
    hi link	csLogicSymbols	Operator
    " Don't highlight same type (List) two different ways.
    hi link	csNewType	NONE
    " I don't think these should be highlighted differently or brightly.
    hi link	csParens	Delimiter
    hi link	csBraces	Delimiter

The first one I think a lot of people would agree since colons don't need to stand out. Keeping the group there is fine, just it shouldn't link to statement (which is the same as `get` which makes more sense to stand out).

The second is updating `||`,  etc to look like an operator since that's what they are. I think that's more correct.

The third is demonstrated in this line:

    static List<string> m_Stuff = new List<string>();

I think List should have the same highlighting on left and right of equals.

The last set I just dislike the excess colours. I'm not sure what the right link is. For now, I'm trying Delimiter but I might drop them to NONE.

**Comment by nickspoons** [comment]
Thanks @idbrii, all good points. I think it's good to have the highlight groups defined but perhaps these settings are too opinionated.

I think the best thing would be to link `csLogicSymbols` to `Operator` as you've done, and not link the others - if people then want to link csParens or csBraces etc. they can do so.
