### ISSUE TITLE
csInterfaceDeclaration is linked but not defined

### ISSUE THREAD

**Issue by idbrii** [nickspoons/vim-cs#7]
I'm guessing that csInterfaceDeclaration existed once upon a time, but no more?

https://github.com/nickspoons/vim-cs/blob/be16cea64f1ce241ca6624161cddece1c684c0a7/syntax/cs.vim#L167

I found a definition for it [in someones nvim files](https://github.com/dunstontc/nvim.d/blob/562436fadd62d2515977717932a9d6f3c8647a40/syntax/cs.vim#L242), but no where else. Didn't try digging through vim/vim.

Is there something I'm missing?

**Comment by nickspoons** [comment]
No, I just had a look through the OmniSharp-vim history and it appears to have been there by itself for 6 years, but never any other reference to it. So let's get rid of it.
